# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='exculdes',
            new_name='excludes',
        ),
    ]
